apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: ztunnel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ztunnel-windows
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: ztunnel-windows-1.0.0
  name: ztunnel-windows
  namespace: istio-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ztunnel-windows
  template:
    metadata:
      annotations:
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      labels:
        app: ztunnel-windows
        app.kubernetes.io/instance: ztunnel-windows
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ztunnel-windows
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: ztunnel-windows-1.0.0
        istio.io/dataplane-mode: none
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - proxy
        - ztunnel
        env:
        - name: ISTIOD_SERVICE_HOST
          value: 10.0.127.250 #clusterIP for istiod
        - name: XDS_ADDRESS
          value: https://10.0.127.250:15012
        - name: CA_ADDRESS
          value: https://10.0.127.250:15012
        - name: ALT_XDS_HOSTNAME
          value: istiod.istio-system.svc
        - name: ALT_CA_HOSTNAME
          value: istiod.istio-system.svc
        - name: USE_ENV_FOR_DEFAULT_ISTIOD_ADDR
          value: "true"
        - name: RUST_LOG
          value: trace
        - name: RUST_BACKTRACE
          value: "1"
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: INPOD_ENABLED
          value: "true"
        - name: INPOD_UDS
          value: \\.\pipe\istio-zds
        - name: INPOD_PORT_REUSE
          value: "false"
        - name: TERMINATION_GRACE_PERIOD_SECONDS
          value: "30"
        - name: IPV6_ENABLED
          value: "false"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        image: acndev.azurecr.io/agentfabric/ztunnel-windows
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: NT AUTHORITY\SYSTEM
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /var/run/ztunnel
          name: cni-ztunnel-sock-dir
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ztunnel
      serviceAccountName: ztunnel
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: istio-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          defaultMode: 420
          name: istio-ca-root-cert
        name: istiod-ca-cert
      - hostPath:
          path: /var/run/ztunnel
          type: DirectoryOrCreate
        name: cni-ztunnel-sock-dir
      - emptyDir: {}
        name: tmp
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
